# Project: model
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = test.o $(RES)
LINKOBJ  = test.o $(RES)
LIBS =  -L"C:/Dev/MinGW/lib" -L"C:/Dev/libs/lib3ds-1.3.0"  
INCS =  -I"C:/Dev/libs/lib3ds-1.3.0" 
CXXINCS =  -I"C:/Dev/MinGW/include"  -I"C:/Dev/libs/lib3ds-1.3.0" 
BIN  = model.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before model.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "model.exe" $(LIBS)

test.o: test.cpp
	$(CPP) -c test.cpp -o test.o $(CXXFLAGS)
